accelerator: cuda
dataset:
  edge_encoder: false
  edge_encoder_name: Bond
  format: PyG
  name: Ecoli
  node_encoder: false
  node_encoder_name: Atom
  resample_negative: true
  split_type: temporal
  task: link_pred
  task_type: classification
  transform: []
gnn:
  act: relu
  agg: mean
  batchnorm: false
  dim_inner: 16
  dropout: 0.1
  head: custom
  layer_type: gatconv
  layers_mp: 3
  layers_post_mp: 2
  layers_pre_mp: 2
  normalize_adj: false
  stage_type: skipsum
  keep_edge: 0.5
model:
  edge_decoding: dot
  graph_pooling: add
  loss_fun: cross_entropy
  type: gnn
  thresh: 0.8
num_workers: 10
optim:
  base_lr: 0.01
  max_epoch: 200
  optimizer: adam
  weight_decay: 5e-4
out_dir: results/temporal_optuned
seed: 2024
tensorboard_each_run: true
train:
  batch_size: 32
  ckpt_period: 100
  eval_period: 1
  sampler: full_batch