out_dir: results/link_predict_debug
tensorboard_each_run: True
seed: 2024
dataset:
  format: PyG
  name: Cora
  task: link_pred
  task_type: classification
  node_encoder: False
  node_encoder_name: Atom
  edge_encoder: False
  edge_encoder_name: Bond
  resample_negative: True
train:
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
  sampler: full_batch
model:
  type: gnn
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: add
gnn:
  layers_pre_mp: 0
  layers_mp: 2
  layers_post_mp: 1
  dim_inner: 64
  layer_type: gcnconv
  stage_type: stack
  batchnorm: False # False
  act: relu # relu
  dropout: 0.0
  agg: add
  normalize_adj: False
  head: custom
optim:
  optimizer: adam
  scheduler: cos
  base_lr: 0.01
  max_epoch: 400 # 200